from unittest.mock import patch

from streamlit.testing.v1 import AppTest


def test_app_renders_properly():
    """Verify that the side-by-side layout loads up basic headers successfully."""
    at = AppTest.from_file("app.py").run()
    assert not at.exception
    # Check that the columns and layout title subheader render properly
    assert at.subheader[0].value == "Source Code"


def test_invalid_syntax_error_handling():
    """Verify that inputting broken code breaks gracefully via validation."""
    # Mock analyze_code to instantly return an invalid block without hitting the web
    with patch("app.analyze_code") as mock_analyze:
        mock_analyze.return_value = {
            "is_valid_code": False,
            "language": "python",
            "extension": ".py",
            "big_o": {
                "time": "Unknown",
                "space": "Unknown",
                "explanation": "Broken syntax.",
            },
            "flaws": ["Invalid syntax."],
            "suggestions": [],
        }

        at = AppTest.from_file("app.py").run()
        at.text_area[0].input("def broken_function(").run()
        at.button[0].click().run()

        results = at.session_state["analysis_results"]
        assert results is not None
        assert "Refactoring aborted" in results["refactored_code"]


def test_empty_input_warning():
    """Ensure submitting spaces or nothing warns the developer explicitly."""
    with patch("app.analyze_code") as mock_analyze:
        mock_analyze.return_value = {
            "is_valid_code": False,
            "language": "python",
            "extension": ".py",
            "big_o": {
                "time": "Unknown",
                "space": "Unknown",
                "explanation": "Blank input.",
            },
            "flaws": ["Empty input."],
            "suggestions": [],
        }

        at = AppTest.from_file("app.py").run()
        at.text_area[0].input("   ").run()
        at.button[0].click().run()

        results = at.session_state["analysis_results"]
        assert results is not None
        assert "Refactoring aborted" in results["refactored_code"]


def test_render_suggestions_no_suggestions():
    """Ensure that the 'No suggestions generated.' message is shown when suggestions are empty."""  # noqa: E501
    at = AppTest.from_file("app.py")

    # Pre-populate the session state just like app.py expects, but with empty suggestions # noqa: E501
    at.session_state.analysis_results = {
        "analysis": {
            "big_o": {"time": "O(1)", "space": "O(1)", "explanation": "Quick test"},
            "flaws": [],
            "suggestions": [],
        },
        "refactored_code": "print('hello')",
        "readme_content": "# Readme",
    }

    # Run the app structure with this mock state
    at.run()

    # Verify the success message was generated by checking all success elements
    assert len(at.success) > 0

    # Make sure your specific message is inside one of the success boxes
    success_messages = [element.value for element in at.success]
    assert "No suggestions generated." in success_messages


def test_analyze_exception_handling():
    """Ensure that if the backend processing crashes, the app catches the exception and displays an error."""  # noqa: E501

    # Target where it's defined: 'analyzer.analyze_code'
    with patch("analyzer.analyze_code") as mock_analyze:
        # Arrange: Force it to blow up with a runtime error
        mock_analyze.side_effect = RuntimeError("Groq API Timeout or Connection Error")

        # Initialize the app *inside* the patch context
        at = AppTest.from_file("app.py").run()

        # Act: Provide valid Python code so it passes the initial validation check
        at.text_area[0].input("print('Hello World')").run()
        at.button[0].click().run()

        # Assert: Verify that an error element was created on screen
        assert len(at.error) > 0

        # Verify that the specific error message is caught and rendered in the UI
        expected_error_msg = "Analysis failed:\nGroq API Timeout or Connection Error"
        assert at.error[0].value == expected_error_msg
