from unittest.mock import patch

from streamlit.testing.v1 import AppTest

from app import _render_flaws_section


def test_app_renders_properly():
    """Verify that the side-by-side layout loads up basic headers successfully."""
    at = AppTest.from_file("app.py").run()
    assert not at.exception
    # Check that the columns and layout title subheader render properly
    assert at.subheader[0].value == "Source Code"


@patch("analyzer.generate_readme")
@patch("analyzer.refactor_code")
@patch("analyzer.analyze_code")
def test_successful_analysis_flow(mock_analyze, mock_refactor, mock_readme):
    """Test the end-to-end analysis workflow from button press to UI updates."""
    # Define our mocked API payloads
    mock_analyze.return_value = {
        "big_o": {
            "time": "O(1)",
            "space": "O(1)",
            "explanation": "Mocked complexity details.",
        },
        "flaws": ["A mock flaw description."],
        "suggestions": ["A mock optimization suggestion."],
    }
    mock_refactor.return_value = "def mocked_code(): pass"
    mock_readme.return_value = "# Mocked README File Content"

    # Spin up our simulated app environment
    at = AppTest.from_file("app.py").run()

    # Locate the Python input box, send code, and hit run
    at.text_area[0].input("def greet():\n    print('hi')").run()
    at.button[0].click().run()

    assert not at.exception

    # Read layout values directly from Streamlit's Markdown element array
    # because layout blocks and expanders render text inside `at.markdown`
    all_markdown_text = [md.value for md in at.markdown]

    # Assert that all the core processing data successfully reached the frontend
    assert any("Time Complexity: O(1)" in text for text in all_markdown_text)
    assert any("Space Complexity: O(1)" in text for text in all_markdown_text)
    assert any("Mocked complexity details." in text for text in all_markdown_text)


def test_invalid_syntax_error_handling():
    """Verify that inputting broken code breaks gracefully via ast validation."""
    at = AppTest.from_file("app.py").run()

    # Pass in invalid, broken syntax to trigger syntax checks
    at.text_area[0].input("def broken_function(").run()
    at.button[0].click().run()

    # Verify that an error element popped up on screen to warn the developer
    assert len(at.error) > 0
    assert "Invalid Python syntax" in at.error[0].value


def test_empty_input_warning():
    """Ensure submitting spaces or nothing warns the developer explicitly."""
    at = AppTest.from_file("app.py").run()

    # Send entirely blank spaces
    at.text_area[0].input("   ").run()
    at.button[0].click().run()

    # Check for the expected Streamlit warning box element
    assert len(at.error) > 0
    assert "Please enter Python code." in at.error[0].value


@patch("app.st")
def test_render_flaws_section_no_flaws(mock_st):
    """Test that the last line (st.success) is reached when there are no flaws."""
    # Arrange: Create an analysis dict with an empty flaws list
    mock_analysis = {"flaws": []}

    # Act: Call the method
    _render_flaws_section(mock_analysis)

    # Assert: Verify that the code skipped the loop and hit the success message
    mock_st.expander.assert_called_once_with("**Identified Flaws**", expanded=False)
    mock_st.success.assert_called_once_with("No major flaws detected.")
    mock_st.write.assert_not_called()


def test_render_suggestions_no_suggestions():
    """Ensure that the 'No suggestions generated.' message is shown when suggestions are empty."""  # noqa: E501
    at = AppTest.from_file("app.py")

    # Pre-populate the session state just like app.py expects, but with empty suggestions # noqa: E501
    at.session_state.analysis_results = {
        "analysis": {
            "big_o": {"time": "O(1)", "space": "O(1)", "explanation": "Quick test"},
            "flaws": [],
            "suggestions": [],
        },
        "refactored_code": "print('hello')",
        "readme_content": "# Readme",
    }

    # Run the app structure with this mock state
    at.run()

    # Verify the success message was generated by checking all success elements
    assert len(at.success) > 0

    # Make sure your specific message is inside one of the success boxes
    success_messages = [element.value for element in at.success]
    assert "No suggestions generated." in success_messages


def test_analyze_exception_handling():
    """Ensure that if the backend processing crashes, the app catches the exception and displays an error."""  # noqa: E501

    # Target where it's defined: 'analyzer.analyze_code'
    with patch("analyzer.analyze_code") as mock_analyze:
        # Arrange: Force it to blow up with a runtime error
        mock_analyze.side_effect = RuntimeError("Groq API Timeout or Connection Error")

        # Initialize the app *inside* the patch context
        at = AppTest.from_file("app.py").run()

        # Act: Provide valid Python code so it passes the initial validation check
        at.text_area[0].input("print('Hello World')").run()
        at.button[0].click().run()

        # Assert: Verify that an error element was created on screen
        assert len(at.error) > 0

        # Verify that the specific error message is caught and rendered in the UI
        expected_error_msg = "Analysis failed:\nGroq API Timeout or Connection Error"
        assert at.error[0].value == expected_error_msg
